### ISSUE TITLE
Use advanced terminal lib to save time

### ISSUE THREAD

**Issue by husayt** [117/alpaca-terminal#3]
@117 i have not used this, but seems like you the aim is a nice terminal style trading dashboard.

From my experience I know that terminal apps look deceptively simple and take more time than originally thought.

One suggestion I have in order to save time, is to use proper terminal library, with lots of high level ui elements ready e.g. tables/navigation/windows/forms and etc.

Something like [terminal-kit](https://www.npmjs.com/package/terminal-kit) or [blessed](https://github.com/chjj/blessed) could save a lot of time

**Comment by 117** [comment]
The goal was speed of execution, and I'm more in favor of a CLI which is truly command based such as '$ alpaca buy <sym> <qty> ...'. For the occasional quick trade and/or account check.

**Comment by husayt** [comment]
Then, less is more indeed
